### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by cjyabraham** [cncf/svg-autocrop#22]
when I run `npm install -g svg-autocrop` I get `npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules`.  So then I used `sudo` and got this error:

```
[~/Sites/svg/input]$ sudo npm install -g svg-autocrop
npm WARN deprecated core-js@2.6.10: core-js@<3.0 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/local/bin/svg-autocrop -> /usr/local/lib/node_modules/svg-autocrop/fix.js

> puppeteer@1.20.0 install /usr/local/lib/node_modules/svg-autocrop/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/svg-autocrop/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/svg-autocrop/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/svg-autocrop/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path:
   '/usr/local/lib/node_modules/svg-autocrop/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/cjyabraham/.npm/_logs/2019-11-28T02_45_25_312Z-debug.log
```

Any ideas on how to resolve?

**Comment by cjyabraham** [comment]
FYI, I ended up installing in a directory from a clone of the source code so resolving this issue isn't urgent.
