### ISSUE TITLE
Error: ENOENT: no such file or directory, scandir 'input'

### ISSUE THREAD

**Issue by Jie-Qiao** [cncf/svg-autocrop#33]
I already created the file input and output using the `mkdir -p svg/input` and `mkdir -p svg/output`. However there still an error.

My node version is: v14.15.1
npm version 6.14.9

```
PS C:\Users\35846\AppData\Roaming\npm\node_modules\svg-autocrop> npm run fix

> svg-autocrop@2.0.36 fix C:\Users\35846\AppData\Roaming\npm\node_modules\svg-autocrop
> node fix.js

Error: ENOENT: no such file or directory, scandir 'input'
    at Object.readdirSync (fs.js:1021:3)
    at getInputFiles (C:\Users\35846\AppData\Roaming\npm\node_modules\svg-autocrop\fix.js:18:37)
    at main (C:\Users\35846\AppData\Roaming\npm\node_modules\svg-autocrop\fix.js:30:30)
    at Object.<anonymous> (C:\Users\35846\AppData\Roaming\npm\node_modules\svg-autocrop\fix.js:72:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'input'
}
```

**Comment by AndreyKozlov1984** [comment]
Hi!
I am a developer of this project. First, I can not guarantee that this WILL work on windows, we never tested it there.
Second, it is expected that there is a folder `input` and `output` , without an `svg` word in it!
Also, consider using `autocrop.cncf.io` website for now, also as a web server, if you have troubles. It is a nice UI around this npm module hosted by CNCF team.
